### ISSUE TITLE
Unable to use remote ATRAC encoder with path

### ISSUE THREAD

**Issue by optroodt** [asivery/webminidisc#11]
First of all, thanks for all the effort you're putting into this project, it's absolutely fantastic!

I'm hosting my own copy of [atrac-api](https://github.com/thinkbrown/atrac-api), but it's behind an nginx reverse proxy and uses a path. I've tested it and it works fine. However, the Encoder Configuration dialog does not allow me to save the changes because the 'ok' button is disabled as soon as I add a path (e.g. `/atrac/`).

<img width="595" alt="Screenshot 2022-10-03 at 09 28 12" src="https://user-images.githubusercontent.com/1515592/193530403-9b5f773b-6445-49ca-8df3-d17931dd4112.png">

**Comment by asivery** [comment]
@optroodt Thank you for reporting the issue. I'll fix it as soon as possible

**Comment by optroodt** [comment]
Thanks, that was quick, it works flawlessly!!
