### ISSUE TITLE
Character conversion problem

### ISSUE THREAD

**Issue by MaxGripe** [asivery/webminidisc#16]
There is a auto-rename problem with "ł"/"Ł" letter of the Polish alphabet. In case if track name or disc name contains it, the character will be replaced with a space. It should be converted to "l"/"L" instead.

**Comment by asivery** [comment]
Thanks for reporting the issue @MaxGripe - I was able to confirm that's an issue, albeit quite a weird one.

**Comment by asivery** [comment]
Fixed in [netmd-js#5269383](https://github.com/cybercase/netmd-js/commit/526938364c3862e6cbbec4ea6d411938a02297e1)

**Comment by asivery** [comment]
Fixed in Web Minidisc Pro in a014be02aeb0bf06a4e82fd7a10b691f35f59d06
