### ISSUE TITLE
Can't wipe certain minidiscs

### ISSUE THREAD

**Issue by FrankSidebottom1** [asivery/webminidisc#17]
I have 6 74 minutes minidiscs of the same brand and time period, 2 of them I can edit on WEB MINIDISC WEBSITE just fine, but the other 4 I can only see tracklist, impossible to wipe or change track order at WEB MINIDISC WEBSITE

https://user-images.githubusercontent.com/128667418/227107155-e6d6d4b1-d49e-4aa0-bb23-ef647fabe7c9.mov

**Comment by asivery** [comment]
@FrankSidebottom1 It seems like the discs are write protected. Let me know if that was the problem.

**Comment by FrankSidebottom1** [comment]
> @FrankSidebottom1 It seems like the discs are write protected. Let me know if that was the problem.

THAT WAS THE PROBLEM! THANK YOU!!!! :)
