### ISSUE TITLE
Oops, something unexpected happened on FLAC decode

### ISSUE THREAD

**Issue by TravelRec** [asivery/webminidisc#23]
Hello all,
thank you for the great tool, it almost works very fine for me! Unfortunately, when dragging some FLAC files to copy on MD, the program crashes. It seems that FLAC bit rat has an influence. WAV and MP3 works well. Recorder type doesn´t matter, tried with MZ-RH1, MZ-N505, MZ-N710.

Best Regards,
TravelRec.

**Comment by asivery** [comment]
Hello there @TravelRec! I am pretty much using the app with FLAC files only, and never encountered the problem you're describing. Would you mind sharing some more info about it?

On the "Oops, something unexpected happened" screen, do you have any logs listed, or just "\<not provided\>"?
Could you also share a screenshot of the JS console (Right click anywhere on the page, select "inspect element", then the console tab at the top then, after it loads, drag a FLAC file in, then look for red text at the bottom).

Best regards,
asivery.

**Comment by torynfarr** [comment]
I'm encountering this as well with seemingly every FLAC file that I have. It was previously working, but as of v1.4.1 I can't write any FLAC files. It goes through the conversion and then fails to write. I also tried with files I had previously been able to write successfully.

![image](https://github.com/asivery/webminidisc/assets/36836551/4870d861-49b8-4eff-8dc8-d95edb37bba7)

![image](https://github.com/asivery/webminidisc/assets/36836551/d9ffd2c9-fad8-4a0e-889e-4f7400feccf3)

I'm using a Sony MZ-NE410.

I tried incognito mode (I'm using Brave). I also tried erasing the disc first. That... I was able to do, but it didn't fix the issue. Still unable to write.

**Comment by torynfarr** [comment]
Diving deeper here, I discovered I can't write WAV files either. I tried using both Brave and Chromium. I'll have to try on another computer. Well... reboot first. Then try another PC.

**Comment by torynfarr** [comment]
On a completely different computer running Windows 11 (with the Zadig driver installed) and using Edge, exactly the same error is occuring:

<img width="403" alt="image" src="https://github.com/asivery/webminidisc/assets/36836551/cb4c1689-9335-492c-88e5-7f35250e7449">

I think there's an issue here - not specific to my PC.

**Comment by torynfarr** [comment]
I figured out what the issue was! Even though I had ample battery life to play music for an extended period of time... I think the device itself (Sony MZ-NE410) has some sort of low battery detection during recording. It was disconnecting itself from my computer the moment I attempted to write anything to it. Put in a fresh battery and everything works fine now 🤷🏻‍♂️

**Comment by asivery** [comment]
@torynfarr Thanks for the thorough diagnosis, I am aware of the devices' issues with recording while on low battery, but it's not something I can fix, at least not easily. The NetMD protocol doesn't seem to support any sort of querying of the current battery charge, so I can't even display an appropriate warning. When low on battery, the machine just disconnects itself. To the software it looks as if someone had just pulled the cable.

**Comment by torynfarr** [comment]
No worries. Totally understand that this is on the device side. I imagine the same behavior would have occurred back in the day with SonicStage.
