### ISSUE TITLE
Web Minidisc Pro no recording files to NetMD

### ISSUE THREAD

**Issue by MarcioAyran** [asivery/webminidisc#27]
Hello
I'm using the Web Minidisc and I tried to use the Web Minidisc Pro with my Sony MZ-N920 MD for recording, but when I drag-and-drop the songs to record a disc, the recording is converted, but the device doesn't record, unlike from the previous version (non-pro Web Minidisc). What can I do to use the Web Minidisc Pro version and avoid this problem?

**Comment by asivery** [comment]
Hello there @MarcioAyran! I need some more info to diagnose the issue you've encountered. What exactly happens after the conversion? Do you have any logs in the JS Console? (Right click on the page -> Inspect Element -> Console tab (at the top))
