### ISSUE TITLE
Sony NW-HD5 support

### ISSUE THREAD

**Issue by Invictaz** [asivery/webminidisc#29]
Reported this issue also on WMD github. 

https://github.com/cybercase/webminidisc/issues/135

**Comment by asivery** [comment]
Hi there @Invictaz! I'd be very happy to work on this, but unfortunately I have no Sony MP3 players, so I have no way to test it, even if I did add support for it (adding support for some device is incredibly frustrating if I don't have that device on hand. I've worked like that before, and don't want to do it again). However, if I ever get my hands on one of those devices, I'll try to add support for it.

**Comment by asivery** [comment]
Thanks to a generous donation from imkidd57_# I am now a proud owner of a Sony NW-HD1, so I might be able to add support for it and other Network Walkmen.
