### ISSUE TITLE
Feature Suggestion: Right-click context menu/Keyboard shortcuts to rename tracks

### ISSUE THREAD

**Issue by Tobio89** [asivery/webminidisc#42]
Hi WebMD devs,

I wondered if you thought about adding one or both of these features:
- Right click context menu for renaming tracks
- A keyboard shortcut to trigger renaming tracks

What do you think?
If you're okay with it, I might be able to add them myself and you guys can test it out?

**Comment by asivery** [comment]
Added in #46
