### ISSUE TITLE
Title is written in 'group format' while there are no groups

### ISSUE THREAD

**Issue by Airell** [asivery/webminidisc#43]
Hi, I found the following issue (in 1.4.2).

Scenario:
Have an existing recording without group and no group `0;title//` format.
~Now add one recording to the end.~
~Now move the new recording to a new position.~
Only move an existing recording to a new position.
After the TOC write, the title is written in 0;title// format.

Device tested: MZ-N707, MZ-N510 .

**Comment by asivery** [comment]
Fixed in https://github.com/cybercase/netmd-js/commit/886d2a23cfab4e4bdde606fd6a81c4c9bb37c6df
