### ISSUE TITLE
connection issue with Hi-MD mode sony NH1

### ISSUE THREAD

**Issue by LBM78** [asivery/webminidisc#50]
hi,

I got the driver for Hi MD installed , its also listing it when selecting "connect to Hi-MD (full)"
![Screenshot 2024-07-07 210325](https://github.com/asivery/webminidisc/assets/172387046/80d5feb0-dd61-45ef-a222-249beee10ab8)

but it then give me the error "Failed to execute 'requestDevice' on 'USB': No device selected."
![Screenshot 2024-07-07 210608](https://github.com/asivery/webminidisc/assets/172387046/9093c14f-aab8-40c7-8a4a-199c6607cad8)
 any idea?

**Comment by asivery** [comment]
@LBM78 Did you go through the unrestricted mode setup? (Insert a normal disc, open menu, homebrew mode shortcuts, upgrade to unrestricted mode)

**Comment by LBM78** [comment]
@asivery yes did that , otherwise it would show HiMD but NetMD. 
![image](https://github.com/user-attachments/assets/fc9cb653-aeea-40f7-81ad-bc533b7c24ab)
![image](https://github.com/user-attachments/assets/483fd717-e9a3-4bc2-9668-d5b1c651014a)

**Comment by asivery** [comment]
@LBM78 I can see that notice on the page - what site are you using? This notice is not a part of this application - you seem to be using a fork. Can you open https://testing.minidisc.wiki/webminidisc-testing instead?

**Comment by LBM78** [comment]
I tried it again and waited till the HiMD was recorgnized as such and clicked "OK" on the "please put a HiMD disc into the player" screen. but now I only get a white screen...

**Comment by LBM78** [comment]
hi, you still looking into it?

**Comment by asivery** [comment]
@LBM78 Hi - yes, I am. Thanks for being so patient. I had some things I needed to resolve first. Can you provide me some more logs? Do you get any errors in the JS console? (Right click anywhere on the page, select "Inspect Element", then the "Console" tab at the top of the page).

**Comment by LBM78** [comment]
hi ,

this is what I get:

![image](https://github.com/user-attachments/assets/7eb0b8b8-eda5-4c91-8ac2-72df3b01e9f1)

**Comment by asivery** [comment]
Oh, wonderful - I found this bug while looking through the codebase randomly, and fixed it a few minutes ago (d3660bc). Please try again now.

**Comment by LBM78** [comment]
@asivery i also have a DS-HMD1 ..  would love to get working as well, so no sonicstage needed... should I open another issue?

**Comment by LBM78** [comment]
@asivery ok, so its working but I cant add AT3+ higher then 132bit 
![image](https://github.com/user-attachments/assets/2e923571-582a-4d4a-bcc0-0a7f6fee0e58)

**Comment by asivery** [comment]
@LBM78 About the DS-HMD1 - please send me its VID and PID codes - I'll add it. As for the second error - follow the instruction provided by the app - open settings from the menu, switch the encoder to remote encoder, and retry.

**Comment by LBM78** [comment]
![image](https://github.com/user-attachments/assets/de55ebfc-29f5-4f62-bc62-15f00da8c6ea)
 DS-HMD1

**Comment by asivery** [comment]
@LBM78 Try again now - homebrew mode support added. Did selecting the encoder let you select other ATRAC variants?

**Comment by LBM78** [comment]
encoder selection worked :)

**Comment by asivery** [comment]
Wonderful, has the issue been resolved then?

**Comment by LBM78** [comment]
NH1 issue, yes, works perfectly.
HMD1 nope, let me raise a seperate issue
