### ISSUE TITLE
Sony DS-HMD1 issue with homebrewed mode

### ISSUE THREAD

**Issue by LBM78** [asivery/webminidisc#54]
Hi,

selected in setting the menu to be shown, but when opening the menue its loading... not showing the extra line "switch to HiMD mode"

![image](https://github.com/user-attachments/assets/a8c6ad6e-84b2-49f9-9d80-0bfc37e28478)

**Comment by LBM78** [comment]
@asivery dont know if this helps
![image](https://github.com/user-attachments/assets/909375fc-29e9-46bb-a740-010088880b4f)

**Comment by asivery** [comment]
@LBM78 Please select "Enter Homebrew mode" instead, then send me a screenshot.

**Comment by LBM78** [comment]
@asivery 

![image](https://github.com/user-attachments/assets/32574152-0582-40ae-a6b8-c47c0fa5cec6)

**Comment by asivery** [comment]
Huh, I see - it seems that device might not be supported in exactly the same way....
Try executing the following code in the WMD JS Console after connecting (do not enter homebrew mode):

```js
exposeAPIToConsole();
```
Then, after you see cyan text:
```js
(async () => {
    const fIface = await interface.factory();
    const code = await fIface.getDeviceCode();
    console.log(code);
})();
```

Then send me a screenshot again.

**Comment by LBM78** [comment]
what I can say from watching the device manager... its native mode seems to be the hiMD mode. with no disc in it, it pops up as drive .... ones you put it a normal MD it will switch to USB mode

![image](https://github.com/user-attachments/assets/ee7bb59c-e844-47fe-bd6b-007944a3683f)

**Comment by LBM78** [comment]
@asivery 
![image](https://github.com/user-attachments/assets/54acfd85-4f75-4ab8-8b84-ba5e57722ef6)

**Comment by LBM78** [comment]
@asivery any news on this one, can I do anything else to get this running :)

**Comment by asivery** [comment]
@LBM78 Updated. Please try again - it was using the wrong factory mode authstring.

**Comment by LBM78** [comment]
fantastic, great work, it works now perfectly.... you can close this one

btw. any interest in getting the Shelfhifi Sony CMT-SE7 to work as well....  it comes back USB Com in the device manager?

**Comment by asivery** [comment]
@LBM78 I don't see the reason why the CMT-SE7 wouldn't be supported - what's the problem with it?

**Comment by LBM78** [comment]
let me open another issue for this one.... I tried it ones , zadig wont see it when pluged in ....
