### ISSUE TITLE
issue with HiMD on MZ-RH1

### ISSUE THREAD

**Issue by LBM78** [asivery/webminidisc#55]
hi,

same issue again trying to switch to HiMD mode
![image](https://github.com/user-attachments/assets/cc6c2055-66d1-4612-a16f-5e59548e3506)

submenue not visible

![image](https://github.com/user-attachments/assets/77b15849-5e44-4b7e-9257-a672af63573b)

**Comment by asivery** [comment]
@LBM78 You have an RH1 of which firmware we don't yet have. If you can dump the firmware, and send it to me, I'll make it work. To do that, open the normal homebrew mode, then from the menu in that mode, select the option that will download the firmware.

**Comment by LBM78** [comment]
[ram_Sony MZ-RH1_Hx1.060.zip](https://github.com/user-attachments/files/16404755/ram_Sony.MZ-RH1_Hx1.060.zip)

**Comment by LBM78** [comment]
@asivery did the zip work ?

**Comment by asivery** [comment]
@LBM78 It did - I just haven't had the time to work on it yet. I will most likely do it in two days' time.

**Comment by asivery** [comment]
@LBM78 It's done, please let me know if it works now :)

**Comment by LBM78** [comment]
just tried it, works perfect !!
btw any chance to have a look at my other request about playlists?

**Comment by asivery** [comment]
@LBM78 Unfortunately playlists are just something that's unimplementable, at least in the web version - I might try and get them working in ElectronWMD though, but definitely not in the next version.
