### ISSUE TITLE
Sony CMT-SE7 not working with WebMD

### ISSUE THREAD

**Issue by LBM78** [asivery/webminidisc#56]
Hi,
here the issue with the SE7.

visible as USB COMM 

zadig driver installed

VID: 054C
PID 0120

wont show as device in WebMD
![image](https://github.com/user-attachments/assets/bc842445-7ed7-4adc-bcc0-6c34267152c7)

![image](https://github.com/user-attachments/assets/ed9273de-c79a-4b3a-9d5b-eb3f202b5bfe)

**Comment by asivery** [comment]
@LBM78 Have you pressed the "NetMD" button on the unit?

**Comment by asivery** [comment]
You need to install Zadig while it's in that mode. Otherwise WMD won't see it

**Comment by LBM78** [comment]
ah perfect 
![image](https://github.com/user-attachments/assets/255fefeb-2c57-4a58-8e72-e53111164355)

![image](https://github.com/user-attachments/assets/6f98d711-e59f-489c-8c4f-1bb861f8d109)


working now thanks

**Comment by asivery** [comment]
Great!
