### ISSUE TITLE
Support for MZ-RH1 firmware Hx1.080

### ISSUE THREAD

**Issue by tp-sy** [asivery/webminidisc#57]
Similar to issue #55, my MZ-RH1 is not supported in HiMD mode in current Web minidisc pro. All the options are greyed out.

Attached is the firmware dump.
[Sony.MZ-RH1_Hx1.080.zip](https://github.com/user-attachments/files/16479183/Sony.MZ-RH1_Hx1.080.zip)

**Comment by LBM78** [comment]
which URL are you using for webMD? try https://testing.minidisc.wiki/webminidisc-testing/

**Comment by tp-sy** [comment]
That works for me, thanks!
