### ISSUE TITLE
issue with HMD1 on version 1.5 switching to HiMD

### ISSUE THREAD

**Issue by LBM78** [asivery/webminidisc#59]
@asivery 
got the same issue again with white screen when switching to hiMD after swapping the disc

![image](https://github.com/user-attachments/assets/65a56587-4990-43fa-a0a2-4132ae5b2c2e)

**Comment by asivery** [comment]
@LBM78 I've been trying to reproduce this issue... Are you sure the disc is not corrupted?

**Comment by LBM78** [comment]
@asivery tested it on https://web.minidisc.wiki/ and it works now... no idea what it was, same disk

**Comment by asivery** [comment]
Oh, what a weird bug, thank you for verifying it works now. :)
