### ISSUE TITLE
[Feature Request]: Add Kanji sector (UTOC#4) writing on the homebrew

### ISSUE THREAD

**Issue by knight-ryu12** [asivery/webminidisc#64]
As we can dump the UTOC in homebrew devices, I found out Kanji/Katakana full-width sector view is missing.

If it isn't hard, I wonder if it's feasible to implement.

**Comment by asivery** [comment]
Added in 3feb6ce / https://github.com/asivery/netmd-tocmanip/commit/4174c7f9e606740b9448e3c45650b23df9158e03
